version: '3'

services:
  django:
    build:
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py collectstatic --noinput  && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    container_name: Oracle
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
